refactor scripts, add default hooks

diff --git a/root/scripts/backup b/root/scripts/backup
--- a/root/scripts/backup
+++ b/root/scripts/backup
@@ -1,59 +1,104 @@
 #!/bin/bash
+if [ -n "${DEBUG}" ]; then set -ex; fi;
 
-usageStr="Usage: (ba)sh $0 <filters: directories, or reponames>";
+usageStr="Usage: (ba)sh $0 <filters: categories, or reponames>";
 
-repoDir="${CGIT_REPODIR:-/home/git/repositories}"; # repositories root dir (must exist)
-archiveDir="${CGIT_ARCHIVEDIR:-$CGIT_REPODIR/.archived}"; # archive dir
-
-oDir="$PWD"; # so we can get back to working dir after task done
+repoDir="${CGIT_REPODIR:-/home/git/repositories}"; # repositories root dir
+archiveDir="${CGIT_ARCHIVEDIR:-$CGIT_REPODIR/.archived}"; # archive dir (must exist)
+repoTracker="${CGIT_BACKUP_LIST:-/tmp/backup_list_of_repos}"; # list of repos to backup, generated before each run
+maxDepth="${CGIT_REPOS_MAXDEPTH:-3}"; # maximum depth to search for repositories to restore
 
 filter="$1"; # filter repos in directories, or by name
-tracker="/tmp/backups"; # keep track of backed up repos
 
-mkdir -p $archiveDir; # ensure dir exists
-cd $repoDir; # set $PWD
+fmtdt    (){    date +"%Y-%m-%dT%H:%M:%S%:z";         } # date format
+eecho    (){>&2 echo "[$(fmtdt)] $@";                 } # echo error
+iecho    (){    echo "[$(fmtdt)] $@";                 } # echo info
 
-# gather repo directories in ${tracker}
-# find
-#   ignore backup files
-#   ignore dirs not ending with .git
-#   filter with $filter
-#   remove path upto repodir
-#   sort / uniq
-find . -maxdepth 3 -type d 2> /dev/null \
-    | grep -v '\.git.tar.gz' \
-    | grep -e '\.git\/' \
-    | grep -e "${filter:=./}" \
-    | sed  -e 's_/[^/]*$__' -e 's_^\./__' \
-    | sort -u \
-    > ${tracker};
+totalRepos=0;   # total repos to restore
+needleRepo=0;   # index of repo currently being processed
+skippedRepos=0; # count of skipped repos
+doneRepos=0;    # count of backed-up repos
+failedRepos=0;  # count of failed repos
 
-# backup each repo in respective category folder inside $archiveDir/
-for line in `cat ${tracker}`;
-do
-    bfile="$archiveDir/$line.tar.gz"; # backup destination tar file
-    sdir="${line%/*}"; # backup source dir
-    repo="${line##*/}"; # repo dir
+onExit () {
+    local xc=$?;
+    trap - EXIT;
+    # clean up
+    if [ -f "${repoTracker}" ]; then rm -f "${repoTracker}" && iecho "Removed file: ${repoTracker}"; fi;
+    iecho "$0 exited with code ${xc}";
+}
+trap onExit EXIT HUP INT QUIT PIPE TERM;
 
-    bdir="${bfile%/*}"; # backup destination parent dir (ensure exists)
-    if [ ! -d "${bdir}" ]; # if not exists
-    then
-        echo "Creating backup dir: $bdir";
-        mkdir -p "${bdir}";
-    fi;
+runBackup () {
+    mkdir -p "$repoDir" "$archiveDir"; # ensure dirs exist
 
-    if [ -f "${bfile}" ]; # if backup exists
-    then
-        echo "Removing existing backup: $line => $bfile";
-        rm -f "${bfile}";
-        # TODO: rename instead of remove??
-    fi;
+    # gather repo directories in ${repoTracker}
+    # find
+    #   all directories till maxdepth
+    #   ignore backup files
+    #   filter non-empty dirs ending in '.git' which actually contain subdirs (like branches/hooks/info/objects/refs etc)
+    #   filter with $filter
+    #   remove subdirs (creates duplicate paths)
+    #   sort / uniq
+    find "${repoDir}" -maxdepth ${maxDepth} -type d 2> /dev/null \
+        | grep -v '\.git.tar.gz' \
+        | grep -e '\.git\/' \
+        | grep -e "${filter:=./}" \
+        | sed  -e 's_/[^/]*$__' \
+        | sort -u \
+        > ${repoTracker};
+    totalRepos="$(cat ${repoTracker} | wc -l)";
 
-    # echo $sdir $repo $bdir;
-    echo "Backing up: $line => $bfile";
-    tar -cvzf "${bfile}" -C "${sdir}" ./${repo};
-    echo; # spacer
-done;
+    if [[ ${totalRepos} -eq 0 ]]; then eecho "Nothing to backup"; exit 1; fi;
 
-cd "$oDir"; # get back to working dir
-echo "Done";
+    # backup each repo in respective category folder inside $archiveDir/
+    for line in `cat ${repoTracker}`;
+    do
+        local repo="${line}";
+        local bfile="${archiveDir}/${repo##${repoDir}/}.tar.gz"; # backup destination tar file
+        local bdir="$(dirname $bfile)"; # backup parent dir, may contain category
+        local cdir="$(dirname ${repo})"; # repo parent dir, may contain category
+
+        ((needleRepo++));
+        iecho "REPO ${needleRepo}/${totalRepos} Fail:${failedRepos} Ok:${doneRepos} Skip:${skippedRepos}";
+        iecho "PATH ${repo##${repoDir}/}";
+        iecho "FILE ${bfile##${repoDir}/}";
+
+        if [ ${bdir} != "${archiveDir}" ] \
+        && [ ! -d "${bdir}" ]; # backup category dir is set and does not exist in ${archiveDir}
+        then
+            iecho "MKDR backup category: ${bdir##${archiveDir}/}";
+            mkdir -p "${bdir}";
+        fi;
+
+        if [ -f "${bfile}" ]; # if backup exists
+        then
+            # eecho "SKIP reason: already exists, won't overwrite";
+            # ((skippedRepos++));
+            #
+            # overwrite old backup with new
+            iecho "REMV existing backup file";
+            rm -f "${bfile}";
+            #
+            # # TODO: rename instead of remove??
+            # mv "${bfile}" "${bfile%.tar.gz}.$(fmtdt).tar.gz";
+        fi;
+
+        tar -cpz \
+            -f "${bfile}" \
+            -C "${cdir}" \
+            "${repo##${cdir}/}";
+        if [[ "$?" -eq 0 ]];
+        then
+            ((doneRepos++));
+            iecho "DONE";
+        else
+            ((failedRepos++));
+            iecho "FAIL";
+        fi;
+        echo; # spacer
+    done;
+}
+
+# if not sourcing, run backup
+[[ "$0" == "$BASH_SOURCE" ]] && runBackup $@;
diff --git a/root/scripts/mirror b/root/scripts/mirror
--- a/root/scripts/mirror
+++ b/root/scripts/mirror
@@ -1,62 +1,174 @@
 #!/bin/bash
+if [ -n "${DEBUG}" ]; then set -ex; fi;
 
-usageStr="Usage: (ba)sh $0";
+usageStr="Usage: (ba)sh $0 \$repourl \$description...";
 
 repoDir="${CGIT_REPODIR:-/home/git/repositories}"; # repositories root dir
+archiveDir="${CGIT_ARCHIVEDIR:-$CGIT_REPODIR/.archived}"; # archive dir (skipped when generating category list)
+git_config="${CGIT_GITCONFIG:-/home/git/.gitconfig}"; # custom git config global (optional)
+hooksDir="${CGIT_HOOKSDIR:-/defaults/hooks}"; # copy custom hooks from this dir
+maxDepth="${CGIT_REPOS_MAXDEPTH:-3}"; # maximum depth to search for repositories
 
-oDir="$PWD"; # so we can get back to working dir after task done
-cd "$repoDir";
+fmtdt    (){    date +"%Y-%m-%dT%H:%M:%S%:z";         } # date format
+eecho    (){>&2 echo "[$(fmtdt)] $@";                 } # echo error
+iecho    (){    echo "[$(fmtdt)] $@";                 } # echo info
 
-# there can be either be multiple directory (as in categories) in repodir e.g
-#	_bare/	(for private projects)
-#	bitbucket/
-#	codeberg/
-#	github/
-#	gitlab/
-#	etc
-# or
-#  repos put directly inside repoDir
+urlToName () { # extract repo name from $1=url, remove ending slash if repo ends with /.git
+    echo "$1" \
+    | sed -r 's/.+\/([^.]+)(\.git)?/\1/' \
+    | sed -e 's/\/$//';
+}
 
-# check if any category dirs exist,
-# i.e. no directory ending with .git in repoDir
-if [ "$(find $repoDir -maxdepth 1 -type d | grep -qe '\.git$' && echo 1)" != "1" ];
+if [ -f "${git_config}" ];
 then
-	# select which dir to put the mirror repository in
-	select opt in $(ls -A --group-directories-first $repoDir);
-	do
-		if [ "$opt" != "" ];
-		then
-			cDir="$opt";
-			break;
-		fi;
-		echo "Invalid option."
-	done;
-
-	if [ ! -d "$repoDir/$cDir" ];
-	then
-		echo "Does not exist: $repoDir/$cDir";
-		exit 1;
-	fi;
-	cd "$repoDir/$cDir"; # repo will be cloned inside category dir
+    iecho "Using global config ${git_config}";
+    export GIT_CONFIG_GLOBAL="${git_config}";
 fi;
 
-read -p "URL:" cUrl; # clone url
-read -p "Description:" rDesc; # repo description
+repoUrl="$1";
+repoName="$(urlToName ${repoUrl}).git";
+repoDesc="${@:2}";
 
-# git clone --shared --recursive --progress "$cUrl";
-git clone \
-	--mirror \
-	--progress \
-	--shared \
-	"$cUrl" \
-;
+repoParentDir="${repoDir}"; # where repo will be created
+# defaults to ${repoDir}, category appended, if exists and chosen
 
-rName=${cUrl##*/}; # extract repo name from url
-rName=${rName%\.git}; # remove .git from name, if exists, we'll add it below
+chooseCategory () {
+    # there can be either multiple directories (as in repo categories) in repoDir e.g
+    #   _bare/  (for private projects)
+    #   bitbucket/
+    #   codeberg/
+    #   github/
+    #   gitlab/
+    #   etc
+    # or
+    #  repos put directly inside repoDir
 
-[[ -f "./$rName.git/description" ]] \
-	&& echo "$rDesc" > "./$rName.git/description" \
-	|| echo "No file: ./$rName.git/description";
+    # so we check if any category dirs exist in ${repoDir}, i.e.
+    # find all directories except
+    #   no directory containing .git
+    #   no directory in ${archiveDir}
+    #   not ${repoDir} itself
+    local categories=$(find "${repoDir}" -type d -maxdepth ${maxDepth} \
+        -not -ipath '*\.git*' -and \
+        -not -ipath "${archiveDir}*" -and \
+        -not -path "${repoDir}" 2>/dev/null);
+    local newCategory="+new"; # create a new category
+    local noCategory="+none"; # no category, make repo under ${repoDir}
 
-cd "$oDir"; # get back to working dir
-echo "Done";
+    # select category only if there is atleast one
+    if [[ "$(echo ${categories} | wc -l)" -gt 0 ]];
+    then
+        # choose which category dir to put the repository in
+        iecho "Select repo category (number):";
+        select opt in $(echo -e "${categories}\n${newCategory}\n${noCategory}" | sed -e "s_${repoDir}/__" | sort);
+        do
+            if [ "${opt}" != "" ] && [ -d "${repoDir}/${opt}" ];
+            then
+                repoParentDir="${repoDir}/${opt}";
+                break;
+            elif [ "${opt}" = "${newCategory}" ] && [ ! -d "${repoDir}/${opt}" ];
+            then
+                read -p "Category Name(required): " categ;
+                if [ -n "${categ}" ]; # can not be empty
+                then
+                    mkdir -p "${repoDir}/${categ}";
+                    repoParentDir="${repoDir}/${categ}";
+                    break;
+                fi;
+            elif [ "${opt}" = "${noCategory}" ] && [ ! -d "${repoDir}/${opt}" ];
+            then
+                repoParentDir="${repoDir}";
+                break;
+            fi;
+            eecho "Invalid repo category. Try again."
+        done;
+    fi;
+}
+
+copyHooks () {
+    local defext="${CGIT_HOOK_DEFAULT_EXTENSION:-.sample}"; # previously '-default'
+    if [ -n "${CGIT_HOOKS}" ]; # comma/space-separated list of hooks e.g "post-receive,post-update"
+    then
+        OLDIFS=${IFS};
+        IFS=' ,'; # separators can be comma and/or space
+        for hook in ${CGIT_HOOKS};
+        do
+            IFS=${OLDIFS};
+            if [ -f "${repoParentDir}/${repoName}/hooks/${hook}" ]; # hook exists
+            then # don't overwrite existing hook
+                echo "Hook \"${hook}\" already exists";
+            else
+                if [ -f "${hooksDir}/${hook}${defext}" ]; # hook exists in custom hooks dir
+                then # copy custom hook
+                    iecho "Copying custom hook \"${hook}\"";
+                    cp "${hooksDir}/${hook}${defext}" "${repoParentDir}/${repoName}/hooks/${hook}";
+                    chmod +x "${repoParentDir}/${repoName}/hooks/${hook}";
+
+                elif [ -f "${repoParentDir}/${repoName}/hooks/${hook}${defext}" ]; # hook exists in repo.git/hooks/
+                then # rename default hook
+                    iecho "Copying default hook \"${hook}\"";
+                    cp "${repoParentDir}/${repoName}/hooks/${hook}${defext}" "${repoParentDir}/${repoName}/hooks/${hook}";
+                    chmod +x "${repoParentDir}/${repoName}/hooks/${hook}";
+
+                else # hook not found
+                    iecho "Could not find hook \"${hook}${defext}\"";
+                fi;
+            fi;
+        done;
+        IFS=${OLDIFS};
+    fi;
+}
+
+setDescription () {
+    # if no description given as ${@:2}, try asking
+    if [ -z "${repoDesc}" ]; then read -p "Description: " repoDesc; fi;
+    # repo description, can be empty
+    if [ ! -d "${repoParentDir}/${repoName}" ];
+    then
+        eecho "No repo found at ${repoParentDir}/${repoName}";
+    elif [ -z "${repoDesc}" ]; # empty description
+    then
+        eecho "Skip setting repo description";
+    else
+        iecho "Setting repo description";
+        echo "${repoDesc}" > "${repoParentDir}/${repoName}/description";
+    fi;
+}
+
+makeMirror () {
+    chooseCategory; # select category if needed
+
+    if [ -z "${repoUrl}" ]; # no clone url given as $1, try asking
+    then
+        read -p "Repo URL(required): " repoUrl;
+        if [ -z "${repoUrl}" ]; # clone url is required
+        then
+            eecho "Repository URL is required";
+            iecho "$usageStr";
+            exit 1;
+        fi;
+        repoName="$(urlToName ${repoUrl}).git"; # update repoName
+    fi;
+
+    if [ -d "${repoParentDir}/${repoName}" ];
+    then
+        eecho "Repository exists. Won't overwrite.";
+        exit 1;
+    else
+        iecho "Cloning inside ${repoParentDir}";
+        # repo will be cloned inside repodir/<optional category dir if exists>
+        git clone \
+            --mirror \
+            --progress \
+            --shared \
+            "${repoUrl}" \
+            "${repoParentDir}/${repoName}" \
+        ; # git clone --shared --recursive --progress "${repoUrl}" "${repoParentDir}/${repoName}" ;
+        setDescription;
+        copyHooks;
+        iecho "Done";
+    fi;
+}
+
+# if not sourcing, make mirror
+[[ "$0" == "$BASH_SOURCE" ]] && makeMirror $@;
diff --git a/root/scripts/restore b/root/scripts/restore
--- a/root/scripts/restore
+++ b/root/scripts/restore
@@ -1,59 +1,95 @@
 #!/bin/bash
+if [ -n "${DEBUG}" ]; then set -ex; fi;
 
-usageStr="Usage: (ba)sh $0 <filters: directories, or reponames>";
+usageStr="Usage: (ba)sh $0 <filters: categories, or reponames>";
 
 repoDir="${CGIT_REPODIR:-/home/git/repositories}"; # repositories root dir
 archiveDir="${CGIT_ARCHIVEDIR:-$CGIT_REPODIR/.archived}"; # archive dir (must exist)
-
-oDir="$PWD"; # so we can get back to working dir after task done
+repoTracker="${CGIT_RESTORE_LIST:-/tmp/restore_list_of_repos}"; # list of repos to restore, generated before each run
+maxDepth="${CGIT_REPOS_MAXDEPTH:-3}"; # maximum depth to search for repositories to restore
 
 filter="$1"; # filter repos in directories, or by name
-tracker="/tmp/restored"; # keep track of restored repos
 
-mkdir -p $repoDir; # ensure dir exists
-cd $archiveDir; # set $PWD
+fmtdt    (){    date +"%Y-%m-%dT%H:%M:%S%:z";         } # date format
+eecho    (){>&2 echo "[$(fmtdt)] $@";                 } # echo error
+iecho    (){    echo "[$(fmtdt)] $@";                 } # echo info
 
-# gather repos in $tracker
-# find
-#   ignore backup files
-#   ignore dirs not ending with .git
-#   filter with $filter
-#   remove path upto repodir
-#   sort / uniq
-find . -maxdepth 3 -type f 2> /dev/null \
-    | grep -e '\.git.tar.gz' \
-    | grep -e "${filter:=./}" \
-    | sed -e 's_^\./__' \
-    | sort -u \
-    > "${tracker}";
+totalRepos=0;   # total repos to restore
+needleRepo=0;   # index of repo currently being processed
+skippedRepos=0; # count of skipped repos
+doneRepos=0;    # count of restored repos
+failedRepos=0;  # count of failed repos
 
-# restore each archived repo in respective folder inside $CGIT_REPODIR
-for line in `cat ${tracker}`;
-do
-    bfile="$line"; # restore source tar file
-    sdir="$repoDir/${line%/*}"; # restore dest dir
-    repo="$repoDir/${line%.tar.gz}"; # repo dir
-    bdir="${line%/*}"; # check if repo parent dir exists
-    # echo -e "line: $line \n sdir: $sdir \n repo: $repo \n bdir: $bdir";
+onExit () {
+    local xc=$?;
+    trap - EXIT;
+    # clean up
+    if [ -f "${repoTracker}" ]; then rm -f "${repoTracker}" && iecho "Removed file: ${repoTracker}"; fi;
+    iecho "$0 exited with code ${xc}";
+}
+trap onExit EXIT HUP INT QUIT PIPE TERM;
 
-    if [ ! -f "${bfile}" ]; # no backup file exists
-    then
-        echo "No backups exist: ${bfile}";
-    elif [ -d "${repo}" ]; # repository exists
-    then
-        echo "Already exists: $line => ${repo}";
-    else
-        if [ ! -d "${sdir}" ]; # repo parent dir does not exist
+runRestore () {
+    mkdir -p "$repoDir" "$archiveDir"; # ensure dirs exist
+
+    # gather archived repos in ${repoTracker}
+    # find
+    #   ignore backup dirs, only need files
+    #   ignore dirs not ending with .git.tar.gz
+    #   filter with $filter (default ./ includes all repos)
+    #   sort / uniq
+    find "${archiveDir}" -maxdepth ${maxDepth} -type f 2> /dev/null \
+        | grep -e '\.git.tar.gz' \
+        | grep -e "${filter:=./}" \
+        | sort -u \
+        > "${repoTracker}";
+    totalRepos="$(cat ${repoTracker} | wc -l)";
+
+    if [[ ${totalRepos} -eq 0 ]]; then eecho "Nothing to restore"; exit 1; fi;
+
+    # restore each archived repo in respective folder inside $CGIT_REPODIR
+    for line in `cat ${repoTracker}`;
+    do
+        local bfile="${line##${archiveDir}/}"; # source git.tar.gz file to restore, $archiveDir removed
+        local repo="${repoDir}/${bfile%.tar.gz}"; # .tar.gz removed, .git untouched, repoDir prepended
+        local cdir="$(dirname ${repo})";      # restore dest dir, may contain category
+
+        ((needleRepo++));
+        iecho "REPO ${needleRepo}/${totalRepos} Fail:${failedRepos} Ok:${doneRepos} Skip:${skippedRepos}";
+        iecho "FROM ${line##${archiveDir}/}";
+        iecho "PATH ${repo##${repoDir}/}";
+
+        if [ ! -f "${line}" ]; # no backup file exists, should never happen unless file vanished somehow
         then
-            echo "Creating category dir: $sdir";
-            mkdir -p "${sdir}";
+            eecho "FAIL backup file not found";
+            ((failedRepos++));
+        elif [ -d "${repo}" ]; # repository exists
+        then
+            eecho "SKIP reason: already exists, won't overwrite";
+            ((skippedRepos++));
+        else
+            if [ ${cdir} != "${repoDir}" ] \
+            && [ ! -d "${cdir}" ]; # repo category dir is set and does not exist in ${repoDir}
+            then
+                iecho "MKDR repo category: ${cdir##${repoDir}/}";
+                mkdir -p "${cdir}";
+            fi;
+
+            tar -xpz \
+                -f "${line}" \
+                -C "${cdir}";
+            if [[ "$?" -eq 0 ]];
+            then
+                ((doneRepos++));
+                iecho "DONE";
+            else
+                ((failedRepos++));
+                iecho "FAIL";
+            fi;
         fi;
+        echo; # spacer
+    done;
+}
 
-        echo "Restoring: $line => ${repo}";
-        tar -xvzf "${bfile}" -C "${sdir}";
-    fi;
-    echo; # spacer
-done;
-
-cd "$oDir"; # get back to working dir
-echo "Done";
+# if not sourcing, run restore
+[[ "$0" == "$BASH_SOURCE" ]] && runRestore $@;
diff --git a/root/scripts/sync b/root/scripts/sync
--- a/root/scripts/sync
+++ b/root/scripts/sync
@@ -1,94 +1,218 @@
 #!/bin/bash
+if [ -n "${DEBUG}" ]; then set -ex; fi;
 
 usageStr="Usage: (ba)sh $0";
 
-repoDir="${CGIT_REPODIR:-/home/git/repositories}"; # repositories root dir
+repoDir="${CGIT_REPODIR:-/home/git/repositories}";          # repositories root dir
 
-isRunning="${CGIT_SYNC_RUNFILE:-/tmp/sync_is_running}"; # don't run multiple sync jobs
-repoTracker="${CGIT_SYNC_LIST:-/tmp/sync_list_of_repos}"; # list of repos to sync, generated before each run
+errorList="${CGIT_SYNC_ERRORLIST:-/tmp/sync_errors.txt}";   # sync error catcher
 ignoreList="${CGIT_SYNC_IGNORELIST:-$repoDir/ignored.txt}"; # list of repos to ignore, format: <category>/<repo>.git
-errorList="${CGIT_SYNC_ERRORLIST:-$repoDir/errors.txt}"; # sync error catcher
-syncJobs="${CGIT_SYNC_JOBS:-1}"; # how many parallel jobs for synchronizing one git repo
+isRunning="${CGIT_SYNC_RUNFILE:-/tmp/sync_is_running}";     # don't run multiple sync jobs
+repoTracker="${CGIT_SYNC_LIST:-/tmp/sync_list_of_repos}";   # list of repos to sync, generated before each run, removed after
 
-if [ -e "$isRunning" ]; # don't run multiple sync jobs
+git_config="${CGIT_GITCONFIG:-/home/git/.gitconfig}"; # custom git config global (optional)
+maxDepth="${CGIT_REPOS_MAXDEPTH:-3}";                 # maximum depth to search for repositories to sync
+maxVM="${CGIT_SYNC_MAXVM:-1024000}";                  # set ulimit for git
+syncJobs="${CGIT_SYNC_JOBS:-2}";                      # how many parallel jobs for synchronizing one git repo
+
+shouldFSCK="${CGIT_SYNC_FSCK:-false}";     # whether to test integrity BEFORE fetch for all repos
+shouldFSCKFile="SYNC_NEED_FSCK";           # alternatively create a file named "SYNC_NEED_FSCK" inside a repo to fsck just for that repo
+shouldRepack="${CGIT_SYNC_REPACK:-false}"; # whether to repack AFTER fetch for all repos
+shouldRepackFile="SYNC_NEED_REPACK";       # alternatively create a file named "SYNC_NEED_REPACK" inside a repo to repack just for that repo
+
+fmtdt    (){    date +"%Y-%m-%dT%H:%M:%S%:z";         } # date format
+fflush   (){    echo "[$(fmtdt)]" > $1;               } # flush file
+eecho    (){>&2 echo "[$(fmtdt)] $@";                 } # echo error
+iecho    (){    echo "[$(fmtdt)] $@";                 } # echo info
+lecho    (){    echo "[$(fmtdt)] $@" >> "$errorList"; } # log error
+
+repoPath (){ # remove repoDir from full repo directory path, previously ${PWD##*/}
+    echo "${PWD##$repoDir/}";
+}
+
+repoSrc  (){ # select first non-push remote
+    git remote -v \
+    | grep -Ee '\((fetch|pull)\)' \
+    | head -n1 \
+    | awk '{print $2}';
+}
+
+if [ -f "${git_config}" ];
 then
-	echo "[$(date)] Still running previous instance. Kill it and remove $isRunning to start sync.";
-	exit 1;
+    iecho "Using global config ${git_config}";
+    export GIT_CONFIG_GLOBAL="${git_config}";
 fi;
 
-# start sync
-echo "$(date)" > $isRunning;
-echo "$(date)" > $errorList; # flush old errors from last run
+ulimit -v ${maxVM}; # limit amount of virtual memory
 
-oDir="$PWD"; # so we can get back to working dir after task done
+oPWD="${PWD}"; # so we can get back to working dir after task done
 
-# # sync clones
-#	  find "$repoDir" -maxdepth 3 2> /dev/null | grep -e '\/\.git$' | sort > /tmp/gitlist;
-#	  while read line;
-#	  do
-#		  cd $(readlink -f ${line%\.git}) ;
-#		  echo "===";
-#		  echo "[$(date)] Location: $PWD";
-#		  echo "Remotes:";
-#		  git remote -v | grep -e '(pull)';
-#		  git pull --all --force --tags --recurse-submodules --update-shallow --progress --allow-unrelated-histories;
-#		  echo "[$(date)] Done";
-#		  echo "===";
-#	  done < /tmp/gitlist;
-#	  rm -f /tmp/gitlist;
+totalRepos=0;   # total repos to sync
+needleRepo=0;   # index of repo currently being processed
+skippedRepos=0; # count of skipped repos
+doneRepos=0;    # count of synced repos
+failedRepos=0;  # count of failed repos
+warnRepos=0;    # count of repos synced with warnings
 
-# gather repo directories in ${tracker}
-find "$repoDir" -maxdepth 3 -type d 2> /dev/null \
-	| grep -e '\.git\/' \
-	| sed 's_\/[^\/]*$__' \
-	| sort -u \
-	> ${repoTracker};
-	# TODO: limit search e.g. grep -e 'gitorious\/' -e 'tex\/' -e 'work\/' |\
-	#
+checkResult () {
+    local task="$1"; # name of task
+    local xc=$2; # exit-code
+    local result=${@:3}; # result 2>&1
+    if [[ "${xc}" -eq 0 ]] \
+    && echo "${result}" | grep -qvEe '^(error|fatal|warning)\:';
+    then
+        iecho "${task} ok";
+        ((doneRepos++));
+    elif echo "${result}" | grep -qEe '^warning\:';
+    then
+        iecho "${task} ok (with warning)";
+        eecho "${result}";
+        ((doneRepos++)); # consided sync success
+        ((warnRepos++));
+        lecho "Warn ${task} $(repoPath)";
+    else
+        eecho "${task} failed";
+        eecho "${result}";
+        lecho "Fail ${task} $(repoPath)";
+        ((failedRepos++));
+    fi;
+}
 
-while read line;
-do
-	cd $(readlink -f $line) ;
-	# echo "[$(date)] Repo Location: ${PWD##*/}";
-	echo "[$(date)] Repo Location: ${PWD##$repoDir/}";
-	remotes="$(git remote -v | grep -e '(push)')";
+onExit () {
+    local xc=$?;
+    trap - EXIT;
+    showErrors; # show errors if any
+    # clean up
+    if [ -f "${repoTracker}" ]; then rm -f "${repoTracker}" && iecho "Removed file: ${repoTracker}"; fi;
+    if [ -f "${isRunning}" ];   then rm -f "${isRunning}"   && iecho "Removed file: ${isRunning}";   fi;
+    iecho "$0 exited with code ${xc}";
+    cd "${oPWD}"; # get back to working dir
+}
+trap onExit EXIT HUP INT QUIT PIPE TERM;
 
-	if [ -z "$remotes" ];
-	then
-		echo "[$(date)] No remote found";
-	else
-		echo "[$(date)] Remote URL: $remotes";
+runFetch () {
+    local remote=$(repoSrc);
+    # iecho "${remote}";
 
-		if grep -q "^${PWD##$repoDir/}" ${ignoreList};
-		then
-			echo "[$(date)] Repository ignored.";
-		else
-			git fetch \
-				--all \
-				--auto-gc \
-				--auto-maintenance \
-				--force \
-				--jobs $syncJobs \
-				--progress \
-				--recurse-submodules=yes \
-				--tags \
-				--update-shallow \
-				-k \
-			;
-			if [ ! $? -eq 0 ];
-			then
-				echo "[$(date)] Sync failed with error.";
-				echo "[$(date)] Repo Location: ${PWD##$repoDir/}" >> $errorList;
-			else
-				echo "[$(date)] Synced.";
-			fi;
-		fi;
-	fi;
+    if [ -z "${remote}" ];
+    then
+        eecho "SYNC skipped: No remote defined (bare-repo)";
+        ((skippedRepos++));
+    else
+        iecho "PULL ${remote}";
 
-	echo "==="; # spacer
-done < $repoTracker;
+        if grep -q "^$(repoPath)" ${ignoreList};
+        then
+            eecho "SYNC skipped: repository ignored";
+            ((skippedRepos++));
+        else
+            local RESULT=$(git fetch \
+                --all \
+                --auto-gc \
+                --auto-maintenance \
+                --force \
+                --jobs ${syncJobs} \
+                --progress \
+                --recurse-submodules=yes \
+                --tags \
+                --update-shallow \
+                -k \
+                2>&1 \
+            );
+            checkResult "SYNC" "$?" "${RESULT}";
+        fi;
+    fi;
+}
 
-rm -f $repoTracker $isRunning; # cleanup
+runFSCK () {
+    if [ -e "${shouldFSCKFile}" ]; then rm -f "${shouldFSCKFile}"; fi;
+    local RESULT=$(git fsck \
+        --full \
+        --strict \
+        --name-objects \
+        2>&1\
+    );
+    checkResult "FSCK" "$?" "${RESULT}";
+}
 
-cd "$oDir"; # get back to working dir
-echo "[$(date)] Done";
+runRepack () {
+    if [ -e "${shouldRepackFile}" ]; then rm -f "${shouldRepackFile}"; fi;
+    local RESULT=$(git repack \
+        -a \
+        -d \
+        --keep-unreachable \
+        --no-reuse-delta \
+        2>&1\
+    );
+    checkResult "PACK" "$?" "${RESULT}";
+}
+
+showErrors () {
+    echo;
+    eecho "==="; # spacer
+    eecho "Errors:";
+    eecho "==="; # spacer
+    cat "${errorList}"; # show errors
+    eecho "==="; # spacer
+}
+
+runSync () {
+    if [ -e "${isRunning}" ]; # don't run multiple sync jobs
+    then
+        eecho "Another running process detected";
+        eecho "Killing it now by removing ${isRunning}";
+        eecho "Run $0 again to (re)start sync";
+        exit 1;
+    fi;
+
+    fflush "${isRunning}"; # start sync
+    fflush "${errorList}"; # flush old errors from last run
+
+    # gather repo directories in ${repoTracker} and update totalrepos
+    # find
+    #   all directories till maxdepth
+    #   filter non-empty dirs ending in '.git' which actually contain subdirs (like branches/hooks/info/objects/refs etc)
+    #   remove subdirs (creates duplicate paths)
+    #   sort + uniq
+    find "${repoDir}" -maxdepth ${maxDepth} -type d 2> /dev/null \
+        | grep -e '\.git\/' \
+        | sed 's_\/[^\/]*$__' \
+        | sort -u \
+        > "${repoTracker}";
+        # TODO: limit search e.g. grep -e 'gitorious\/' -e 'tex\/' -e 'work\/' |\
+        #
+    totalRepos="$(cat ${repoTracker} | wc -l)";
+
+    if [[ ${totalRepos} -eq 0 ]]; then eecho "Nothing to sync"; exit 1; fi;
+
+    while read line;
+    do
+        # if ${isRunning} is removed, exit immediately
+        if [ ! -e "${isRunning}" ];
+        then
+            eecho "SYNC stopped.";
+            eecho "Runtime indicator file (${isRunning}) vanished.";
+            lecho "Exit SYNC reason: missing indicator ${isRunning}";
+            exit 1;
+        fi;
+
+        cd $(readlink -f ${line}); # get inside repo
+
+        ((needleRepo++));
+        iecho "REPO ${needleRepo}/${totalRepos} Fail:${failedRepos} Ok:${doneRepos} Skip:${skippedRepos} Warn:${warnRepos}";
+        iecho "PATH $(repoPath)";
+
+        # run integrity check if enabled via envvar or file
+        if [ "${shouldFSCK}" = "true" ] || [ -e "${shouldFSCKFile}" ]; then runFSCK; fi;
+
+        runFetch;
+
+        # run repack if enabled via envvar or file
+        if [ "${shouldRepack}" = "true" ] || [ -e "${shouldRepackFile}" ]; then runRepack; fi;
+
+        echo "==="; # spacer
+    done < "${repoTracker}";
+}
+
+# if not sourcing, run sync
+[[ "$0" == "$BASH_SOURCE" ]] && runSync $@;
