update README,makefile,scripts, add backup/restore scripts, send lighttpd logs to stdout via fifo

diff --git a/root/scripts/bareinit b/root/scripts/bareinit
--- a/root/scripts/bareinit
+++ b/root/scripts/bareinit
@@ -1,68 +1,97 @@
 #!/bin/bash
 
-REPODIR="/home/git/repositories/_bare"
+usageStr="Usage: (ba)sh $0 \$reponame(no .git) \$description...";
 
-#get dotfiles dir path from running file
-filepath=`readlink -f $0`;
-rootdir=${filepath%/*};
+repoDir="${CGIT_REPODIR:-/home/git/repositories}"; # repositories root dir
+hooksDir="${CGIT_HOOKSDIR:-/defaults/hooks}"; # copy custom hooks from this dir
 
-# if [ -z "$1" ];
-# then
-# 	echo "Usage: sh $0 \$reponame(no .git) \$description";
-# 	exit 1;
-# fi;
+oDir="$PWD"; # so we can get back to working dir after task done
+cd "$repoDir";
 
-rpn="$1";
-shift;
+rpn="$1"; shift;
 repodesc="$@";
+
+# there can be either be multiple directory (as in categories) in repodir e.g
+#	_bare/	(for private projects)
+#	bitbucket/
+#	codeberg/
+#	github/
+#	gitlab/
+#	etc
+# or
+#  repos put directly inside repoDir
+
+# check if any category dirs exist,
+# i.e. no directory ending with .git in repoDir
+if [ "$(find $repoDir -maxdepth 1 -type d | grep -qe '\.git$' && echo 1)" != "1" ];
+then
+	# select which dir to put the mirror repository in
+	select opt in $(ls -A --group-directories-first $repoDir);
+	do
+		if [ "$opt" != "" ];
+		then
+			cDir="$opt";
+			break;
+		fi;
+		echo "Invalid option."
+	done;
+
+	if [ ! -d "$repoDir/$cDir" ];
+	then
+		echo "Does not exist: $repoDir/$cDir";
+		exit 1;
+	fi;
+	cd "$repoDir/$cDir"; # repo will be cloned inside category dir
+    bareDir="$repoDir/$cDir"; # directory for bare repositories, so they don't mix with mirrored repos
+else
+    bareDir="$repoDir"; # all types of repos in repoDir
+fi;
 
 if [ -z "$rpn" ];
 then
 	read -p "Name(required, no .git): " rpn;
 	if [ -z "$rpn" ];
 	then
-	 	echo "Usage: sh $0 \$reponame(no .git) \$description";
+		echo "$usageStr";
 		exit 1;
 	else
 		:
 	fi;
 fi;
 
-reponame="$rpn.git";
+reponame="$rpn.git"; # add .git to name
 
-if [ -d "$REPODIR/$reponame" ];
+if [ -d "$bareDir/$reponame" ];
 then
 	echo "Repository exists.";
+	exit 1;
 else
-	echo "Initializing git at: $REPODIR/$reponame";
-	mkdir -p "$REPODIR/$reponame";
-	cd "$REPODIR/$reponame";
-	#init bare git
-	git init --bare --shared;
-fi;
+	echo "Initializing bare repository at: $bareDir/$reponame";
+	mkdir -p "$bareDir/$reponame";
+	cd "$bareDir/$reponame";
+	git init --bare --shared; #initialize bare git repository
 
-
-# write description
-if [ -z "$repodesc" ];
-then
-	read -p "Description(optional):" repodesc;
-	if [ -z "$repodesc" ];
+	if [ -z "$repodesc" ];    # write description
 	then
-		:
+		read -p "Description(optional):" repodesc;
+		if [ -z "$repodesc" ];
+		then
+			:
+		else
+			echo "Writing description";
+			echo "$repodesc" > "$bareDir/$reponame/description";
+		fi;
 	else
 		echo "Writing description";
-	        echo "$repodesc" > "$REPODIR/$reponame/description";
+		echo "$repodesc" > "$bareDir/$reponame/description";
 	fi;
-else
-	echo "Writing description";
-        echo "$repodesc" > "$REPODIR/$reponame/description";
+
+	mkdir -p "$bareDir/$reponame/hooks";
+	# echo "Copying post receive hook..."; # creates checkouts in $CGIT_PROJECTDIR
+	# cp "$hooksDir/post-receive-default" "$bareDir/$reponame/hooks/post-receive";
+	echo "Copying post update hook..."; # updates git-server-info
+	cp "$hooksDir/post-update-default" "$bareDir/$reponame/hooks/post-update";
 fi;
 
-#copy post receive hook from rootdir;
-# echo "Copying post receive hook...";
-# cp "/defaults/hooks/post-receive-default" "$REPODIR/$reponame/hooks/post-receive";
-
-echo "Copying post update hook...";
-cp "/defaults/hooks/post-update-default" "$REPODIR/$reponame/hooks/post-update";
-
-#return 0;
+cd "$oDir"; # get back to working dir
+echo "Done";
diff --git a/root/scripts/mirror b/root/scripts/mirror
--- a/root/scripts/mirror
+++ b/root/scripts/mirror
@@ -1,37 +1,62 @@
 #!/bin/bash
 
-REPODIR="/home/git/repositories";
+usageStr="Usage: (ba)sh $0";
 
-select opt in $(ls $REPODIR);
-do
-	if [ "$opt" != "" ]; then
-                cDir="$opt";
-		break;
-	fi;
-	#else
-	echo "Invalid option."
-done;
+repoDir="${CGIT_REPODIR:-/home/git/repositories}"; # repositories root dir
 
-if [ ! -d "$REPODIR/$cDir" ];
+oDir="$PWD"; # so we can get back to working dir after task done
+cd "$repoDir";
+
+# there can be either be multiple directory (as in categories) in repodir e.g
+#	_bare/	(for private projects)
+#	bitbucket/
+#	codeberg/
+#	github/
+#	gitlab/
+#	etc
+# or
+#  repos put directly inside repoDir
+
+# check if any category dirs exist,
+# i.e. no directory ending with .git in repoDir
+if [ "$(find $repoDir -maxdepth 1 -type d | grep -qe '\.git$' && echo 1)" != "1" ];
 then
-	echo "Does not exist: $REPODIR/$cDir";
-	exit 1;
+	# select which dir to put the mirror repository in
+	select opt in $(ls -A --group-directories-first $repoDir);
+	do
+		if [ "$opt" != "" ];
+		then
+			cDir="$opt";
+			break;
+		fi;
+		echo "Invalid option."
+	done;
+
+	if [ ! -d "$repoDir/$cDir" ];
+	then
+		echo "Does not exist: $repoDir/$cDir";
+		exit 1;
+	fi;
+	cd "$repoDir/$cDir"; # repo will be cloned inside category dir
 fi;
 
-read -p "URL:" cUrl;
-read -p "Description:" rDesc;
-
-oDir="$PWD";
-cd "$REPODIR/$cDir";
+read -p "URL:" cUrl; # clone url
+read -p "Description:" rDesc; # repo description
 
 # git clone --shared --recursive --progress "$cUrl";
-git clone --mirror --shared --progress "$cUrl";
+git clone \
+	--mirror \
+	--progress \
+	--shared \
+	"$cUrl" \
+;
 
-rName=${cUrl##*/};
-rName=${rName%\.git};
+rName=${cUrl##*/}; # extract repo name from url
+rName=${rName%\.git}; # remove .git from name, if exists, we'll add it below
 
-# [[ -f "./$rName/.git/description" ]] && echo "$rDesc" > "./$rName/.git/description" || echo "No file: ./$rName/.git/description";
-[[ -f "./$rName.git/description" ]] && echo "$rDesc" > "./$rName.git/description" || echo "No file: ./$rName.git/description";
+[[ -f "./$rName.git/description" ]] \
+	&& echo "$rDesc" > "./$rName.git/description" \
+	|| echo "No file: ./$rName.git/description";
 
-cd "$oDir";
+cd "$oDir"; # get back to working dir
 echo "Done";
diff --git a/root/scripts/sync b/root/scripts/sync
--- a/root/scripts/sync
+++ b/root/scripts/sync
@@ -1,58 +1,94 @@
 #!/bin/bash
 
-REPODIR="/home/git/repositories";
-RUNFILE="/tmp/gitsynclonesrun";
+usageStr="Usage: (ba)sh $0";
 
-if [ -e $RUNFILE ];
+repoDir="${CGIT_REPODIR:-/home/git/repositories}"; # repositories root dir
+
+isRunning="${CGIT_SYNC_RUNFILE:-/tmp/sync_is_running}"; # don't run multiple sync jobs
+repoTracker="${CGIT_SYNC_LIST:-/tmp/sync_list_of_repos}"; # list of repos to sync, generated before each run
+ignoreList="${CGIT_SYNC_IGNORELIST:-$repoDir/ignored.txt}"; # list of repos to ignore, format: <category>/<repo>.git
+errorList="${CGIT_SYNC_ERRORLIST:-$repoDir/errors.txt}"; # sync error catcher
+syncJobs="${CGIT_SYNC_JOBS:-1}"; # how many parallel jobs for synchronizing one git repo
+
+if [ -e "$isRunning" ]; # don't run multiple sync jobs
 then
-    echo "[$(date)] Still running previous instance.";
-    exit 1;
-else
-#     # sync clones
-#     find "$REPODIR" -maxdepth 3 2> /dev/null | grep -e '\/\.git$' | sort > /tmp/gitlist;
-#     while read line;
-#     do
-#         cd $(readlink -f ${line%\.git}) ;
-#         echo "===";
-#         echo "[$(date)] Location: $PWD";
-#         echo "Remotes:";
-#         git remote -v | grep -e '(pull)';
-#         git pull --all --force --tags --recurse-submodules --update-shallow --progress --allow-unrelated-histories;
-#         # git fetch --all --force --tags --recurse-submodules=yes --update-shallow --progress -k --jobs 3;
-#         echo "[$(date)] Done";
-#         echo "===";
-#     done < /tmp/gitlist;
-#     rm -f /tmp/gitlist;
+	echo "[$(date)] Still running previous instance. Kill it and remove $isRunning to start sync.";
+	exit 1;
+fi;
 
-    # sync mirrors
-    find "$REPODIR" -maxdepth 3 -type d 2> /dev/null |\
-	grep -e '\.git\/' |\
-	sed 's_\/[^\/]*$__' |\
-	uniq | sort > /tmp/gitlist;
+# start sync
+echo "$(date)" > $isRunning;
+echo "$(date)" > $errorList; # flush old errors from last run
 
-    echo "$(date)" > $RUNFILE;
+oDir="$PWD"; # so we can get back to working dir after task done
 
-    while read line;
-    do
-        cd $(readlink -f $line) ;
-        echo "===";
+# # sync clones
+#	  find "$repoDir" -maxdepth 3 2> /dev/null | grep -e '\/\.git$' | sort > /tmp/gitlist;
+#	  while read line;
+#	  do
+#		  cd $(readlink -f ${line%\.git}) ;
+#		  echo "===";
+#		  echo "[$(date)] Location: $PWD";
+#		  echo "Remotes:";
+#		  git remote -v | grep -e '(pull)';
+#		  git pull --all --force --tags --recurse-submodules --update-shallow --progress --allow-unrelated-histories;
+#		  echo "[$(date)] Done";
+#		  echo "===";
+#	  done < /tmp/gitlist;
+#	  rm -f /tmp/gitlist;
 
-        # echo "[$(date)] Repo Location: ${PWD##*/}";
-        echo "[$(date)] Repo Location: ${PWD##$REPODIR/}";
+# gather repo directories in ${tracker}
+find "$repoDir" -maxdepth 3 -type d 2> /dev/null \
+	| grep -e '\.git\/' \
+	| sed 's_\/[^\/]*$__' \
+	| sort -u \
+	> ${repoTracker};
+	# TODO: limit search e.g. grep -e 'gitorious\/' -e 'tex\/' -e 'work\/' |\
+	#
 
-        remotes="$(git remote -v | grep -e '(push)')"; # fetch/push for mirrors, pull/push for normal repos
+while read line;
+do
+	cd $(readlink -f $line) ;
+	# echo "[$(date)] Repo Location: ${PWD##*/}";
+	echo "[$(date)] Repo Location: ${PWD##$repoDir/}";
+	remotes="$(git remote -v | grep -e '(push)')";
+
 	if [ -z "$remotes" ];
 	then
 		echo "[$(date)] No remote found";
 	else
 		echo "[$(date)] Remote URL: $remotes";
-		git fetch --all --force --tags --recurse-submodules=yes --update-shallow --progress -k --jobs 2;
+
+		if grep -q "^${PWD##$repoDir/}" ${ignoreList};
+		then
+			echo "[$(date)] Repository ignored.";
+		else
+			git fetch \
+				--all \
+				--auto-gc \
+				--auto-maintenance \
+				--force \
+				--jobs $syncJobs \
+				--progress \
+				--recurse-submodules=yes \
+				--tags \
+				--update-shallow \
+				-k \
+			;
+			if [ ! $? -eq 0 ];
+			then
+				echo "[$(date)] Sync failed with error.";
+				echo "[$(date)] Repo Location: ${PWD##$repoDir/}" >> $errorList;
+			else
+				echo "[$(date)] Synced.";
+			fi;
+		fi;
 	fi;
 
-        echo "[$(date)] Done";
-        echo "===";
-    done < /tmp/gitlist;
+	echo "==="; # spacer
+done < $repoTracker;
 
-    rm -f $RUNFILE;
-    rm -f /tmp/gitlist;
-fi;
+rm -f $repoTracker $isRunning; # cleanup
+
+cd "$oDir"; # get back to working dir
+echo "[$(date)] Done";
